// `halo enable <plugin-name>` (ADR-0017 / D11 §3): 同梱プラグイン(@tsurupong/halo-plugins)の
// dist を実行時解決した絶対パスで指すランチャーを `.halo/ports/<port>.d/<name>/` へ生成する。
// monorepo 外(npm インストール / .halo/ports へのコピー配布)で plugins/<name>/ の相対パス
// ランチャーが壊れる問題への対処 (D11 §3 追記)。CLI はロジックを持たず registry を写すだけ。
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { chmod as nodeChmod } from 'node:fs/promises';
import { BUNDLED_PLUGINS, type BundledPlugin } from '@tsurupong/halo-plugins/registry';
import type { ParsedArgs } from '../args.js';
import type { ExitCode } from '../exit-codes.js';
import { EXIT } from '../exit-codes.js';
import type { Io } from '../io.js';
import type { CliFs } from '../core-ext/fs.js';

export interface EnableDeps {
  fs: CliFs;
  /** ランチャーへ実行権限を付与する。既定は node:fs/promises の chmod。 */
  chmod?: (path: string, mode: number) => Promise<void>;
  /** `@tsurupong/halo-plugins` の package.json 絶対パスを解決する。既定は require.resolve 相当。 */
  resolvePluginsPackageJson?: () => string;
}

/** `require.resolve('@tsurupong/halo-plugins/package.json')` 相当 (D11 §3 追記)。 */
function defaultResolvePluginsPackageJson(): string {
  const require = createRequire(import.meta.url);
  return require.resolve('@tsurupong/halo-plugins/package.json');
}

function listAvailable(): string {
  const names = BUNDLED_PLUGINS.map((p) => p.name).sort();
  return `利用可能な同梱プラグイン:\n${names.map((n) => `  ${n}`).join('\n')}\n`;
}

function launcherScript(distPath: string): string {
  return `#!/bin/sh
# generated by \`halo enable\` — do not edit (ADR-0017 / D11 §3)
HALO_LAUNCHER_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
export HALO_LAUNCHER_DIR
exec node "${distPath}" "$@"
`;
}

/** `plugin.env` のテンプレート値中の `{PORTS_DIR}` を実際の絶対パスへ展開する。 */
function resolveEnv(
  env: Record<string, string> | undefined,
  portsDir: string,
): Record<string, string> | undefined {
  if (env === undefined) return undefined;
  const resolved: Record<string, string> = {};
  for (const [key, value] of Object.entries(env)) {
    resolved[key] = value.replaceAll('{PORTS_DIR}', portsDir);
  }
  return resolved;
}

export async function enableCommand(
  parsed: ParsedArgs,
  io: Io,
  deps: EnableDeps,
): Promise<ExitCode> {
  const name = parsed.positionals[0];
  if (name === undefined) {
    io.streams.err(listAvailable());
    return EXIT.OK;
  }

  const plugin = BUNDLED_PLUGINS.find((p): p is BundledPlugin => p.name === name);
  if (!plugin) {
    io.streams.err(`error: unknown plugin '${name}'\n`);
    io.streams.err(listAvailable());
    return EXIT.USAGE;
  }

  const resolvePackageJson = deps.resolvePluginsPackageJson ?? defaultResolvePluginsPackageJson;
  const distRoot = join(dirname(resolvePackageJson()), 'dist');
  const chmodFn = deps.chmod ?? ((path, mode) => nodeChmod(path, mode));

  const cwd = io.flags.cwd.replace(/\/$/, '');
  const portsDir = `${cwd}/.halo/ports`;
  const targetDir = `${portsDir}/${plugin.port}.d/${plugin.name}`;

  await deps.fs.mkdir(targetDir, { recursive: true });

  const resolvedEnv = resolveEnv(plugin.env, portsDir);
  const manifest =
    resolvedEnv !== undefined ? { ...plugin.manifest, env: resolvedEnv } : plugin.manifest;
  await deps.fs.writeFile(`${targetDir}/plugin.json`, `${JSON.stringify(manifest, null, 2)}\n`);

  for (const entry of plugin.entries) {
    const scriptPath = `${targetDir}/${entry.script}`;
    const distPath = join(distRoot, entry.dist);
    await deps.fs.writeFile(scriptPath, launcherScript(distPath));
    await chmodFn(scriptPath, 0o755);
  }

  io.streams.err(`enabled ${plugin.name} -> ${targetDir}\n`);
  return EXIT.OK;
}
