// plugin.json manifest, .harness.yml, and kg:// URI types (D1 §2, §1.8, §4).
// Single source of truth for the JSON Schemas generated by scripts/gen-schema.ts.

/**
 * A knowledge-graph node reference (D1 §4). Not a filesystem path.
 *
 * Format: `kg://<node-type>/<node-id>` where node-type is one of
 * `context` / `aggregate` / `term` / `document` / `decision` and node-id is a
 * kebab-case slug unique within its type. loop-audit verifies existence.
 *
 * @format uri
 */
export type KgUri = string;

/** The eight executable ports a plugin can belong to (D1 §2). */
export type Port =
  'task-source' | 'context' | 'executor' | 'gate' | 'sink' | 'on-fail' | 'runtime' | 'trigger';

/**
 * Minimum autonomy level a plugin (typically a sink) requires to run (D1 §1.5).
 * Cumulative: L3 ⊇ L2 ⊇ L1. When undeclared the core treats the plugin as the
 * safest side (effectively L3 — skipped at L1/L2).
 */
export type MinAutonomy = 'L1' | 'L2' | 'L3';

/**
 * plugin.json manifest (D1 §2). Every plugin declares this in its directory so
 * the core has the metadata needed to launch it across the process boundary.
 */
export interface PluginManifest {
  /** Plugin identifier (e.g. `@halo/plugin-*`). */
  name: string;
  /**
   * The plugin's own semver.
   *
   * @pattern ^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$
   */
  version: string;
  /** The port this plugin belongs to. */
  port: Port;
  /** Relative (or absolute) path to the plugin's main JS entry module.
   *  Spawned as `process.execPath <entry>` by the core (ADR-0018). */
  entry: string;
  /**
   * Execution order (numeric-prefix equivalent). Defaults to the filename's
   * numeric prefix when omitted.
   *
   * @asType integer
   */
  order?: number;
  /** Autonomy filter for sinks etc. Undeclared = safest side (skipped < L3). */
  minAutonomy?: MinAutonomy;
  /**
   * Per-plugin execution timeout in seconds. Defaults to the port default.
   *
   * @asType integer
   * @minimum 1
   */
  timeoutSec?: number;
  /** Environment variables injected at launch (name → default value / reference). */
  env?: Record<string, string>;
  /** Auxiliary JS entries (e.g. trigger install/uninstall, runtime check/test),
   *  keyed by role name. Not spawned by the core loop. */
  aux?: Record<string, string>;
}

/**
 * A single kind definition inside `.harness.yml` (D1 §1.8): which runtimes and
 * prompt template a task kind resolves to.
 */
export interface HarnessKind {
  /**
   * Directory names under `runtime.d`.
   *
   * @minItems 1
   */
  runtimes: string[];
  /** Path to the prompt template. */
  prompt: string;
}

/**
 * `.harness.yml` — required at the target repository root (D1 §1.8). Maps each
 * `kind:<name>` label (default `code`) to its runtimes and prompt, and declares
 * the repository-level safety caps the core enforces.
 *
 * The safety fields live here (rather than in a profile) because `.harness.yml` is
 * committed and is itself a loop-audit protected file (ADR-0004): the cap an
 * unattended run obeys stays reviewable in git and cannot be raised by the agent.
 */
export interface HarnessYml {
  /**
   * Task kind definitions keyed by kind name.
   *
   * @minProperties 1
   */
  kinds: Record<string, HarnessKind>;
  /**
   * Repository-level ceiling on the autonomy level (ADR-0004). The effective level
   * is `min(resolved AUTONOMY, maxAutonomy)`, so neither a profile nor `--autonomy`
   * can exceed it. Omitted → no repository ceiling (profile/CLI decide alone).
   */
  maxAutonomy?: MinAutonomy;
  /**
   * Extra paths the audit gate protects from agent self-modification, on top of the
   * built-in set (`CLAUDE.md`, `PROMPT.md`, `.harness.yml`, `.claude/settings.json`).
   * Repo-relative glob patterns where a single star matches within one path segment
   * and a double star matches across segments (for example `packages/plugins/src/gate-`
   * followed by a double star). Use this when the harness maintains itself, to keep
   * the gate implementation out of the agent's reach.
   */
  protectedPaths?: string[];
}
