// Port I/O types for the eight executable ports (D1 §1.1–1.7).
// Single source of truth for the JSON Schemas generated by scripts/gen-schema.ts.

import type { KgUri } from './manifest.js';

// ─── ① task-source (D1 §1.1) ───────────────────────────────────────────────

/** Fetch the next ready task (one). */
export interface TaskSourceNext {
  op: 'next';
}

/** Record task completion. */
export interface TaskSourceComplete {
  op: 'complete';
  task_id: string;
  /** @format uri */
  pr_url: string;
}

/** Record task failure. */
export interface TaskSourceFail {
  op: 'fail';
  task_id: string;
  reason: string;
  /** @asType integer @minimum 0 */
  retry_count: number;
}

/** task-source input, discriminated by `op` (D1 §1.1). */
export type TaskSourceIn = TaskSourceNext | TaskSourceComplete | TaskSourceFail;

/** task-source output for `op=next` (D1 §1.1). */
export interface TaskSourceOut {
  /** `null` means no ready task; the core exits 0 immediately. */
  task_id: string | null;
  /** Task title. */
  title?: string;
  /** Task body (requirement text). */
  body?: string;
  /**
   * `kind:<name>` label; defaults to `code`.
   *
   * @default "code"
   */
  kind?: string;
  /** Frozen-requirement references as kg:// URIs; loop-audit verifies existence. */
  spec_refs?: KgUri[];
  /** Parallel write-conflict avoidance (Phase 5, optional). */
  write_set?: string[];
}

// ─── ② context (D1 §1.2) ────────────────────────────────────────────────────

/** A context fragment, concatenated by the core in descending priority. */
export interface Fragment {
  /** e.g. `codegraph` / `knowledge` / `recent-failures`. */
  source: string;
  /** Text to inject. */
  content: string;
  /**
   * Larger = higher priority; the core concatenates descending and truncates.
   *
   * @asType integer
   */
  priority: number;
}

/** context output (D1 §1.2). Input is the task-source `op=next` output. */
export interface ContextOut {
  fragments: Fragment[];
}

// ─── ③ executor (D1 §1.3) ───────────────────────────────────────────────────

/** Execution budget for the executor. */
export interface ExecutorBudget {
  /**
   * Turn ceiling.
   *
   * @asType integer
   * @default 40
   */
  max_turns: number;
  /**
   * Timeout in seconds.
   *
   * @asType integer
   * @default 900
   */
  timeout_sec: number;
  /**
   * Per-run USD ceiling passed through to the executor runtime's budget stop
   * (ADR-0021). Optional; absent = no per-run cost ceiling (MINOR addition).
   */
  max_budget_usd?: number;
}

/** executor input (D1 §1.3). */
export interface ExecutorIn {
  /** Prompt to run (context concatenated, prior failures re-injected). */
  prompt: string;
  /** Absolute path of the disposable worktree. */
  workdir: string;
  budget: ExecutorBudget;
}

/** Executor status; anything other than `done` routes to the failure path. */
export type ExecutorStatus = 'done' | 'stuck' | 'timeout';

/** executor output (D1 §1.3). */
export interface ExecutorOut {
  status: ExecutorStatus;
  /** Summary of the execution result. */
  summary: string;
  /** Optional cost info (ccusage-equivalent) for observability. */
  cost?: Record<string, unknown>;
}

// ─── ④ gate (D1 §1.4) ───────────────────────────────────────────────────────

/** gate input (D1 §1.4). */
export interface GateIn {
  task_id: string;
  /** Absolute worktree path under inspection. */
  workdir: string;
  changed_files: string[];
  /**
   * Worktree base commit (the HEAD captured at worktree creation). When present,
   * diff-based gates inspect `git diff <base>` so BOTH committed and uncommitted
   * changes are audited (D4 §4.2); without it, gates fall back to `git diff HEAD`
   * and an executor that commits its work would escape inspection.
   */
  base?: string;
}

/** gate output, emitted on fail only (D1 §1.4). */
export interface GateOut {
  /** e.g. `coverage 87% < 90%`. */
  reason: string;
  /** e.g. `src/order.ts のテスト不足`. */
  hint?: string;
  /** Name of the failing gate, e.g. `30-test`. */
  gate?: string;
}

// ─── ⑤ sink (D1 §1.5) ───────────────────────────────────────────────────────

/** sink input (D1 §1.5). Side effects only, no output. */
export interface SinkIn {
  task_id: string;
  /** Absolute worktree path of the artifact. */
  workdir: string;
  /** executor's run summary. */
  summary: string;
}

// ─── ⑥ on-fail (D1 §1.6) ────────────────────────────────────────────────────

/** on-fail input (D1 §1.6). Side effects only, no output. */
export interface OnFailIn {
  task_id: string;
  reason: string;
  /** @asType integer @minimum 0 */
  retry_count: number;
  /** Failing gate name; `stuck`/`timeout` when executor-originated. */
  gate?: string;
  /** Absolute worktree path. */
  workdir?: string;
}

// ─── ⑦ runtime (D1 §1.7) ────────────────────────────────────────────────────

/** runtime script input, shared by setup/check/test (D1 §1.7). */
export interface RuntimeIn {
  /** Absolute worktree path. */
  workdir: string;
  /** Narrowing for check/test (optional). */
  changed_files?: string[];
}
